/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author ivan97
 */
public class ViewPrincipalMDI extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipalMDI
     */
    public ViewPrincipalMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        if_view_cliente = new javax.swing.JInternalFrame();
        if_view_empleado = new javax.swing.JInternalFrame();
        if_view_medicamentos = new javax.swing.JInternalFrame();
        if_view_proveedores = new javax.swing.JInternalFrame();
        if_view_usuarios = new javax.swing.JInternalFrame();
        if_view_login = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jmi_clientes = new javax.swing.JMenuItem();
        jmi_empleados = new javax.swing.JMenuItem();
        jmi_medicamentos = new javax.swing.JMenuItem();
        jmi_proveedores = new javax.swing.JMenuItem();
        jmi_usuarios = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        if_view_cliente.setClosable(true);
        if_view_cliente.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_view_cliente.setMaximizable(true);
        if_view_cliente.setResizable(true);
        if_view_cliente.setVisible(false);

        javax.swing.GroupLayout if_view_clienteLayout = new javax.swing.GroupLayout(if_view_cliente.getContentPane());
        if_view_cliente.getContentPane().setLayout(if_view_clienteLayout);
        if_view_clienteLayout.setHorizontalGroup(
            if_view_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        if_view_clienteLayout.setVerticalGroup(
            if_view_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(if_view_cliente);
        if_view_cliente.setBounds(40, 10, 590, 210);

        if_view_empleado.setClosable(true);
        if_view_empleado.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_view_empleado.setMaximizable(true);
        if_view_empleado.setResizable(true);
        if_view_empleado.setVisible(false);

        javax.swing.GroupLayout if_view_empleadoLayout = new javax.swing.GroupLayout(if_view_empleado.getContentPane());
        if_view_empleado.getContentPane().setLayout(if_view_empleadoLayout);
        if_view_empleadoLayout.setHorizontalGroup(
            if_view_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        if_view_empleadoLayout.setVerticalGroup(
            if_view_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(if_view_empleado);
        if_view_empleado.setBounds(220, 120, 160, 150);

        if_view_medicamentos.setClosable(true);
        if_view_medicamentos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_view_medicamentos.setMaximizable(true);
        if_view_medicamentos.setResizable(true);
        if_view_medicamentos.setVisible(false);

        javax.swing.GroupLayout if_view_medicamentosLayout = new javax.swing.GroupLayout(if_view_medicamentos.getContentPane());
        if_view_medicamentos.getContentPane().setLayout(if_view_medicamentosLayout);
        if_view_medicamentosLayout.setHorizontalGroup(
            if_view_medicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        if_view_medicamentosLayout.setVerticalGroup(
            if_view_medicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(if_view_medicamentos);
        if_view_medicamentos.setBounds(40, 10, 590, 210);

        if_view_proveedores.setClosable(true);
        if_view_proveedores.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_view_proveedores.setMaximizable(true);
        if_view_proveedores.setResizable(true);
        if_view_proveedores.setVisible(false);

        javax.swing.GroupLayout if_view_proveedoresLayout = new javax.swing.GroupLayout(if_view_proveedores.getContentPane());
        if_view_proveedores.getContentPane().setLayout(if_view_proveedoresLayout);
        if_view_proveedoresLayout.setHorizontalGroup(
            if_view_proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        if_view_proveedoresLayout.setVerticalGroup(
            if_view_proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(if_view_proveedores);
        if_view_proveedores.setBounds(40, 10, 590, 210);

        if_view_usuarios.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_view_usuarios.setMaximizable(true);
        if_view_usuarios.setVisible(false);

        javax.swing.GroupLayout if_view_usuariosLayout = new javax.swing.GroupLayout(if_view_usuarios.getContentPane());
        if_view_usuarios.getContentPane().setLayout(if_view_usuariosLayout);
        if_view_usuariosLayout.setHorizontalGroup(
            if_view_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        if_view_usuariosLayout.setVerticalGroup(
            if_view_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(if_view_usuarios);
        if_view_usuarios.setBounds(40, 10, 590, 210);

        if_view_login.setClosable(true);
        if_view_login.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_view_login.setMaximizable(true);
        if_view_login.setResizable(true);
        if_view_login.setVisible(false);

        javax.swing.GroupLayout if_view_loginLayout = new javax.swing.GroupLayout(if_view_login.getContentPane());
        if_view_login.getContentPane().setLayout(if_view_loginLayout);
        if_view_loginLayout.setHorizontalGroup(
            if_view_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        if_view_loginLayout.setVerticalGroup(
            if_view_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(if_view_login);
        if_view_login.setBounds(40, 10, 590, 210);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        jmi_clientes.setMnemonic('s');
        jmi_clientes.setText("Clientes");
        fileMenu.add(jmi_clientes);

        jmi_empleados.setMnemonic('a');
        jmi_empleados.setText("Empleados");
        fileMenu.add(jmi_empleados);

        jmi_medicamentos.setText("Medicamentos");
        fileMenu.add(jmi_medicamentos);

        jmi_proveedores.setText("Proveedores");
        fileMenu.add(jmi_proveedores);

        jmi_usuarios.setText("Usuarios");
        fileMenu.add(jmi_usuarios);

        jmi_salir.setMnemonic('x');
        jmi_salir.setText("salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        fileMenu.add(jmi_salir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmi_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipalMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    public javax.swing.JInternalFrame if_view_cliente;
    public javax.swing.JInternalFrame if_view_empleado;
    public javax.swing.JInternalFrame if_view_login;
    public javax.swing.JInternalFrame if_view_medicamentos;
    public javax.swing.JInternalFrame if_view_proveedores;
    public javax.swing.JInternalFrame if_view_usuarios;
    public javax.swing.JMenuItem jmi_clientes;
    public javax.swing.JMenuItem jmi_empleados;
    public javax.swing.JMenuItem jmi_medicamentos;
    public javax.swing.JMenuItem jmi_proveedores;
    public javax.swing.JMenuItem jmi_salir;
    public javax.swing.JMenuItem jmi_usuarios;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
