/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author equipo hp
 */
public class ViewCliente extends javax.swing.JPanel {

    /**
     * Creates new form ViewCliente
     */
    public ViewCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtf_id_cliente = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apell_pat = new javax.swing.JTextField();
        jtf_apell_mat = new javax.swing.JTextField();
        jtf_calle = new javax.swing.JTextField();
        jtf_colonia = new javax.swing.JTextField();
        jtf_ciudad = new javax.swing.JTextField();
        jtf_estado = new javax.swing.JTextField();
        jb_nuevo = new javax.swing.JButton();
        jb_agregar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_buscar = new javax.swing.JButton();
        jb_actualizar = new javax.swing.JButton();
        jb_usuario = new javax.swing.JButton();
        jb_regresar = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLIENTES");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 140, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("id");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 40, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("nombre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido Paterno");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido Matreno");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Calle");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Colonia");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ciudad");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estado");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));
        add(jtf_id_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, -1));
        add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, -1));
        add(jtf_apell_pat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 150, -1));
        add(jtf_apell_mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, -1));
        add(jtf_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, -1));
        add(jtf_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 150, -1));
        add(jtf_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 150, -1));
        add(jtf_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 150, -1));

        jb_nuevo.setBackground(new java.awt.Color(0, 0, 0));
        jb_nuevo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jb_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jb_nuevo.setText("Nuevo");
        add(jb_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, 40));

        jb_agregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\equipo hp\\Downloads\\users_add2.png")); // NOI18N
        jb_agregar.setText("Agregar");
        add(jb_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 120, 40));

        jb_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        jb_modificar.setText("Modificar");
        add(jb_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 120, -1));

        jb_eliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\equipo hp\\Downloads\\trashcan_delete.png")); // NOI18N
        jb_eliminar.setText("Eliminar");
        add(jb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 110, -1));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jb_buscar.setText("Buscar");
        add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 110, 40));

        jb_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        jb_actualizar.setText("Actualizar");
        add(jb_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 120, 40));

        jb_usuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\equipo hp\\Downloads\\user_group.png")); // NOI18N
        jb_usuario.setText("Usuario");
        add(jb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 110, 40));

        jb_regresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\equipo hp\\Downloads\\undo.png")); // NOI18N
        jb_regresar.setText("Regresar");
        add(jb_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 110, 40));

        jbtn_primero.setText("<");
        add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 50, -1));

        jbtn_anterior.setText("<<");
        add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jbtn_siguiente.setText(">>");
        add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jbtn_ultimo.setText(">");
        add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 90, 50, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dark_blue_wallpaper_by_malkowitch-d6iuhnh.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 403));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JButton jb_actualizar;
    public javax.swing.JButton jb_agregar;
    public javax.swing.JButton jb_buscar;
    public javax.swing.JButton jb_eliminar;
    public javax.swing.JButton jb_modificar;
    public javax.swing.JButton jb_nuevo;
    public javax.swing.JButton jb_regresar;
    public javax.swing.JButton jb_usuario;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JTextField jtf_apell_mat;
    public javax.swing.JTextField jtf_apell_pat;
    public javax.swing.JTextField jtf_calle;
    public javax.swing.JTextField jtf_ciudad;
    public javax.swing.JTextField jtf_colonia;
    public javax.swing.JTextField jtf_estado;
    public javax.swing.JTextField jtf_id_cliente;
    public javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
