/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author ivan97
 */
public class ViewLogin extends javax.swing.JPanel {

    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtn_entrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jpf_contrasena = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtf_usuario1 = new javax.swing.JTextField();
        jbtn_entrar1 = new javax.swing.JButton();
        jpf_contrasena1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        jLabel1.setText("Usuario:");

        jbtn_entrar.setText("Entrar");

        jLabel2.setText("Contraseña:");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 200, 260));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));
        add(jtf_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 140, -1));

        jbtn_entrar1.setText("Entrar");
        add(jbtn_entrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));
        add(jpf_contrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 140, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dark_blue_wallpaper_by_malkowitch-d6iuhnh.jpg"))); // NOI18N
        add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 476));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_fondo;
    public javax.swing.JButton jbtn_entrar;
    public javax.swing.JButton jbtn_entrar1;
    public javax.swing.JPasswordField jpf_contrasena;
    public javax.swing.JPasswordField jpf_contrasena1;
    public javax.swing.JTextField jtf_usuario;
    public javax.swing.JTextField jtf_usuario1;
    // End of variables declaration//GEN-END:variables
}
