/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author equipo hp
 */
public class View_Empleado extends javax.swing.JPanel {

    /**
     * Creates new form View_Empleado
     */
    public View_Empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtn_nuevo = new javax.swing.JButton();
        jtf_estado = new javax.swing.JTextField();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jtf_telefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbtn_eliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtf_id_empleado = new javax.swing.JTextField();
        jbtn_buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_usuario = new javax.swing.JButton();
        jcb_cargo = new javax.swing.JComboBox<>();
        jbtn_regresar = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apell_pat = new javax.swing.JTextField();
        jtf_apell_mat = new javax.swing.JTextField();
        jtf_calle = new javax.swing.JTextField();
        jtf_colonia = new javax.swing.JTextField();
        jtf_ciudad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtn_anterior = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMPLEADO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 170, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido materno");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Calle");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jbtn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jbtn_nuevo.setText("Nuevo");
        jbtn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_nuevoActionPerformed(evt);
            }
        });
        add(jbtn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 120, -1));
        add(jtf_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 150, -1));

        jbtn_agregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\equipo hp\\Downloads\\users_add2.png")); // NOI18N
        jbtn_agregar.setText("Agregar");
        add(jbtn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 120, 40));

        jbtn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        jbtn_modificar.setText("Modificar");
        add(jbtn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 120, -1));
        add(jtf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 150, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefono");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jbtn_eliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\equipo hp\\Downloads\\trashcan_delete.png")); // NOI18N
        jbtn_eliminar.setText("Eliminar");
        add(jbtn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 110, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombre");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        add(jtf_id_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 150, -1));

        jbtn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jbtn_buscar.setText("Buscar");
        add(jbtn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 110, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cargo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 50, 20));

        jbtn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        jbtn_actualizar.setText("Actualizar");
        add(jbtn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 120, -1));

        jbtn_usuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\equipo hp\\Downloads\\user_group.png")); // NOI18N
        jbtn_usuario.setText("Usuario");
        add(jbtn_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 110, 40));

        jcb_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vendedor", "gerente" }));
        add(jcb_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 150, -1));

        jbtn_regresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\equipo hp\\Downloads\\undo.png")); // NOI18N
        jbtn_regresar.setText("Regresar");
        add(jbtn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 110, 40));

        jbtn_primero.setText("<");
        add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 60, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Colonia");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ciudad");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, -1));
        add(jtf_apell_pat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, -1));

        jtf_apell_mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_apell_matActionPerformed(evt);
            }
        });
        add(jtf_apell_mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, -1));
        add(jtf_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 150, -1));
        add(jtf_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 150, -1));
        add(jtf_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jbtn_anterior.setText("<<");
        add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Apellido paterno");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jbtn_siguiente.setText(">>");
        add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, 30));

        jbtn_ultimo.setText(">");
        add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 60, 30));

        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dark_blue_wallpaper_by_malkowitch-d6iuhnh.jpg"))); // NOI18N
        add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_nuevoActionPerformed

    private void jtf_apell_matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_apell_matActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_apell_matActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_fondo;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_buscar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_regresar;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JButton jbtn_usuario;
    public javax.swing.JComboBox<String> jcb_cargo;
    public javax.swing.JTextField jtf_apell_mat;
    public javax.swing.JTextField jtf_apell_pat;
    public javax.swing.JTextField jtf_calle;
    public javax.swing.JTextField jtf_ciudad;
    public javax.swing.JTextField jtf_colonia;
    public javax.swing.JTextField jtf_estado;
    public javax.swing.JTextField jtf_id_empleado;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
